// Generated by gencpp from file rgbdslam/rgbdslam_ros_ui.msg
// DO NOT EDIT!


#ifndef RGBDSLAM_MESSAGE_RGBDSLAM_ROS_UI_H
#define RGBDSLAM_MESSAGE_RGBDSLAM_ROS_UI_H

#include <ros/service_traits.h>


#include <rgbdslam/rgbdslam_ros_uiRequest.h>
#include <rgbdslam/rgbdslam_ros_uiResponse.h>


namespace rgbdslam
{

struct rgbdslam_ros_ui
{

typedef rgbdslam_ros_uiRequest Request;
typedef rgbdslam_ros_uiResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct rgbdslam_ros_ui
} // namespace rgbdslam


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rgbdslam::rgbdslam_ros_ui > {
  static const char* value()
  {
    return "cba5e21e920a3a2b7b375cb65b64cdea";
  }

  static const char* value(const ::rgbdslam::rgbdslam_ros_ui&) { return value(); }
};

template<>
struct DataType< ::rgbdslam::rgbdslam_ros_ui > {
  static const char* value()
  {
    return "rgbdslam/rgbdslam_ros_ui";
  }

  static const char* value(const ::rgbdslam::rgbdslam_ros_ui&) { return value(); }
};


// service_traits::MD5Sum< ::rgbdslam::rgbdslam_ros_uiRequest> should match
// service_traits::MD5Sum< ::rgbdslam::rgbdslam_ros_ui >
template<>
struct MD5Sum< ::rgbdslam::rgbdslam_ros_uiRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rgbdslam::rgbdslam_ros_ui >::value();
  }
  static const char* value(const ::rgbdslam::rgbdslam_ros_uiRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rgbdslam::rgbdslam_ros_uiRequest> should match
// service_traits::DataType< ::rgbdslam::rgbdslam_ros_ui >
template<>
struct DataType< ::rgbdslam::rgbdslam_ros_uiRequest>
{
  static const char* value()
  {
    return DataType< ::rgbdslam::rgbdslam_ros_ui >::value();
  }
  static const char* value(const ::rgbdslam::rgbdslam_ros_uiRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rgbdslam::rgbdslam_ros_uiResponse> should match
// service_traits::MD5Sum< ::rgbdslam::rgbdslam_ros_ui >
template<>
struct MD5Sum< ::rgbdslam::rgbdslam_ros_uiResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rgbdslam::rgbdslam_ros_ui >::value();
  }
  static const char* value(const ::rgbdslam::rgbdslam_ros_uiResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rgbdslam::rgbdslam_ros_uiResponse> should match
// service_traits::DataType< ::rgbdslam::rgbdslam_ros_ui >
template<>
struct DataType< ::rgbdslam::rgbdslam_ros_uiResponse>
{
  static const char* value()
  {
    return DataType< ::rgbdslam::rgbdslam_ros_ui >::value();
  }
  static const char* value(const ::rgbdslam::rgbdslam_ros_uiResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RGBDSLAM_MESSAGE_RGBDSLAM_ROS_UI_H
